"""added description field to venues model

Revision ID: 0a4d2bd899df
Revises: 37e23417605c
Create Date: 2021-02-13 17:18:36.250256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4d2bd899df'
down_revision = '37e23417605c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'description')
    # ### end Alembic commands ###
