"""added new fields to the models

Revision ID: 37e23417605c
Revises: 536bead814d3
Create Date: 2021-02-13 16:12:24.537278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e23417605c'
down_revision = '536bead814d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('losses', sa.String(length=10), nullable=True))
    op.add_column('teams', sa.Column('wins', sa.String(length=10), nullable=True))
    op.add_column('venues', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image')
    op.drop_column('teams', 'wins')
    op.drop_column('teams', 'losses')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
