"""added apg field to model

Revision ID: aaed8fc3c09b
Revises: cd621788126c
Create Date: 2021-02-14 15:07:55.855077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaed8fc3c09b'
down_revision = 'cd621788126c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('apg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'apg')
    # ### end Alembic commands ###
