"""added logo field to team model

Revision ID: bf67b7853eb6
Revises: 0a4d2bd899df
Create Date: 2021-02-13 17:26:29.032545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf67b7853eb6'
down_revision = '0a4d2bd899df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column(
        'logo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo')
    # ### end Alembic commands ###
