"""added players model

Revision ID: cd621788126c
Revises: bf67b7853eb6
Create Date: 2021-02-14 14:59:42.715876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd621788126c'
down_revision = 'bf67b7853eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('team', sa.String(length=50), nullable=False),
                    sa.Column('mpg', sa.Float(), nullable=True),
                    sa.Column('ppg', sa.Float(), nullable=True),
                    sa.Column('rpg', sa.Float(), nullable=True),
                    sa.Column('team_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
