"""updated player model with new field

Revision ID: d1c94dff85f9
Revises: 2fb1ed1e09c7
Create Date: 2021-03-03 21:05:48.768735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c94dff85f9'
down_revision = '2fb1ed1e09c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column(
        'player_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'player_number')
    # ### end Alembic commands ###
