"""added missing second team id field to the events model

Revision ID: d8c486ae145c
Revises: aaed8fc3c09b
Create Date: 2021-02-16 16:22:01.400858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c486ae145c'
down_revision = 'aaed8fc3c09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column(
        'team_id_two', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'teams', ['team_id_two'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'team_id_two')
    # ### end Alembic commands ###
