"""added nullable contrains to events keys

Revision ID: ebd5ce68a186
Revises: edaad99f4f48
Create Date: 2021-02-22 17:51:08.824671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd5ce68a186'
down_revision = 'edaad99f4f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'team_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('events', 'team_id_two',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('events', 'venue_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'venue_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('events', 'team_id_two',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('events', 'team_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
