"""added new score field to event model and change field name

Revision ID: edaad99f4f48
Revises: 8d47c39a5449
Create Date: 2021-02-20 01:25:15.667472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaad99f4f48'
down_revision = '8d47c39a5449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('team_one_score', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('team_two_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'team_two_score')
    op.drop_column('events', 'team_one_score')
    # ### end Alembic commands ###
